name: CookieCutterDL
experiment_group: v0.0
n_gpu: 1

seed: null # Fix seed for reproducibility

arch:
  type: IdentityModel
  args: {}

train_data_loader:
  type: RandomVectorDataLoader
  args:
    num_samples: 1000
    vector_size: 100

validation_data_loader:
  type: RandomVectorDataLoader
  args:
    num_samples: 1000
    vector_size: 100

optimizer:
  type: Adam
  args:
    lr: 0.001
    weight_decay: 0
    amsgrad: true

loss:
  type: "MSELoss"
  args: {}

metrics:
  - mse_metric

lr_scheduler:
  type: StepLR
  args:
    step_size: 50
    gamma: 0.1

trainer:
  epochs: 5
  save_dir: "saved/"
  save_period: 1
  verbosity: 2
  monitor: "min val_loss"
  early_stop: 10
  wandb: False
  codecarbon_save_api: false
